name: Build and test

on:
  pull_request:
    branches: [ main ]

jobs:
  install:
    name: 'build and test'
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - run: node --version
      - run: npm run build

      - name: Save public folder
        uses: actions/upload-artifact@v3
        with:
          name: public
          if-no-files-found: error
          path: public
      - name: Chrome UI test 
        run: npm run test:e2e:ci