name: Build, test, and deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: node --version
      - run: npm install
      - run: npm run build
      - name: Save public folder
        uses: actions/upload-artifact@v3
        with:
          name: public
          if-no-files-found: error
          path: public
      - name: Save .cache folder
        uses: actions/upload-artifact@v3
        with:
          name: .cache
          if-no-files-found: error
          path: .cache
      - name: Save start-server-and-test folder
        uses: actions/upload-artifact@v3
        with:
          name: start-server-and-test
          if-no-files-found: error
          path: node_modules/start-server-and-test
      - name: Save gh-pages folder
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          if-no-files-found: error
          path: node_modules/gh-pages
      
  deploy:
    needs: install
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Test
        run: echo "?"
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Deploy GitHub Pages
      #   run: npm run deploy-only
      # - name: Deploy to GitHub Pages
      #  uses: actions/deploy-pages@v2
      #  artifact-name: public
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: public
          path: public
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # The folder the action should deploy.
