name: Build, test, and deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: node --version
      - run: npm install
      - run: npm run build
      - name: Save public folder
        uses: actions/upload-artifact@v3
        with:
          name: public
          if-no-files-found: error
          path: public
      - name: Save .cache folder
        uses: actions/upload-artifact@v3
        with:
          name: .cache
          if-no-files-found: error
          path: .cache
      - name: Save start-server-and-test folder
        uses: actions/upload-artifact@v3
        with:
          name: start-server-and-test
          if-no-files-found: error
          path: node_modules/start-server-and-test
      - name: Save gh-pages folder
        uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          if-no-files-found: error
          path: node_modules/gh-pages
      
  cypress:
    needs: install
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: public
          path: public
      - name: Download .cache artifacts
        uses: actions/download-artifact@v3
        with:
          name: .cache
          path: .cache/
      - name: Download start-server-and-test artifacts
        uses: actions/download-artifact@v3
        with:
          name: start-server-and-test
          path: node_modules/start-server-and-test
      - name: Chrome UI test 
        run: npm run test:e2e:ci    
      
  deploy:
    #needs: cypress
    needs: install
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    #environment:
    #  name: github-pages
    #  url: ${{ steps.deploy.outputs.page_url }}
    
    #permissions:
    #  pages: write      # to deploy to Pages
    #  id-token: write   # to verify the deployment originates from an appropriate source

    #environment:
    #  name: github-pages
    #  url: ${{ steps.deployment.outputs.page_url }}
    
    #permissions:
    #  contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Debug
      #  run: echo "${{ steps.deploy.outputs.page_url }}"
      #- name: Download build artifacts
      #  uses: actions/download-artifact@v3
      #  with:
      #    name: public
      #    path: public
      #- name: Deploy 🚀
      #  id: deployment
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #    folder: public

      #- name: Deploy to GitHub Pages
      #  id: deployment
      #  uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
      #- name: Debug
      #  run: echo "${{ steps.deploy.outputs.page_url }}"
